In [1]:
#Trying to predict petal_length from sepal length and sepal_width
#We are going to use gradient descent. So the batch size is the whole training dataset

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import math

In [3]:
#Load the iris dataset
df = pd.read_csv ("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", names = ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"])
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
X = df.iloc[:,:2]
t = df.iloc[:,2]

In [5]:
X_train, X_test, t_train, t_test = train_test_split(X,t,test_size=0.30, random_state=42)

In [6]:
X_train = np.asarray(X_train)
X_test = np.asarray(X_test)
t_train = np.asarray(t_train)
t_test = np.asarray(t_test)
t_train.shape

(105,)

In [7]:
#Now let's create the neural network
#We have one hidden layer
#Two input nodes, two nodes in the hidden layer and one node in the output layer
# The activation function of the hidden layer is going to be the sigmoid function 
# In the output layer there won't be an activation function, since we have standard regression
#    x1------>0------\
#                     0-->
#    x2------>0------/
#def init_params():
    #Lets now create the weight matrix W1 for the first layer. W1 is a 2x2 matrix
    # W1 = [[w11, w21]
    #       [w12, w22]]
W1 = np.random.normal(size=(2,2))

    #Lets now create the weight matrix W2 for the second layer. W2 is a 1x2 matrix
    # W2 = [[w11, w21]]

W2 = np.random.normal(size=(1,2))
    #return W1, W2
print(W1)
print(W2)

[[ 0.80227628 -0.07933043]
 [-0.37014444 -1.38566429]]
[[-1.09213897 -0.55063417]]


In [8]:
def sigmoid(a: np.ndarray):
    z = 1 / (1 + np.exp(-a))
    return z
        
        

In [9]:
a = np.array([1,2])
print(a.shape)

(2,)


In [10]:
def forwardPassing(X: np.ndarray, W1: np.ndarray, W2: np.ndarray):
    A1 = np.dot(W1, X.T)
    Z1 = sigmoid(A1)
    Z2 = np.dot(W2, Z1)
    return A1, Z1, Z2
 

In [11]:
#A1, Z1, Z2 = forwardPassing(X_train, W1, W2)
#print((Z2 - t_train).shape)
#print(Z1[0].T.shape)
#print(((Z2 - t_train) * Z1[0]).shape)
#X_train.shape
#print(W2.T[0])
#dw1_1 = W2.T[0] * np.dot((2 * (Z2 - t_train) * Z1[0] * (1 - Z1[0])), X_train)
#dw1_2 = W2.T[1] * np.dot((2 * (Z2 - t_train) * Z1[1] * (1 - Z1[1])), X_train)
#dW1 = np.vstack((dw1_1, dw1_2))
#print(dW1)
#print(dw1_1)
#print(dw1_2)

In [12]:
def loss(X: np.ndarray, t: np.ndarray, W1: np.ndarray, W2: np.ndarray):
    return np.sum(np.square(forwardPassing(X, W1, W2)[2] - t))

In [13]:
print(loss(X_train, t_train, W1, W2))

2882.7562669886966


In [14]:
def backPropagation(W1: np.ndarray, W2: np.ndarray, Z1: np.ndarray, Z2: np.ndarray, X: np.ndarray, t: np.ndarray):
    dW2 = 2* np.dot((Z2 - t), Z1.T)
    print(dW2)
    dw1_1 = W2.T[0] * np.dot((2 * (Z2 - t_train) * Z1[0] * (1 - Z1[0])), X)
    dw1_2 = W2.T[1] * np.dot((2 * (Z2 - t_train) * Z1[1] * (1 - Z1[1])), X)
    dW1 = np.vstack((dw1_1, dw1_2))
    print(dW1)
    return dW1, dW2
    

In [15]:
#dW1, dW2 = backPropagation(W1, W2, Z1, Z2, X_train, t_train)

In [16]:
def updateParams(W1: np.ndarray, W2: np.ndarray, dW1: np.ndarray, dW2: np.ndarray, alpha: float) -> tuple:
    W1 = W1 - alpha * dW1 
    W2 = W2 - alpha * dW2 
    return W1, W2

In [17]:
#print(W1)
#print(dW1)
#updateParams(W1, W2, dW1, dW2, 1)

In [18]:
def gradientDescent(X: np.ndarray, t: np.ndarray, W1: np.ndarray, W2: np.ndarray, iterations: int, alpha: float):
    for i in range(iterations):
        A1, Z1, Z2 = forwardPassing(X, W1, W2)
        dW1, dW2 = backPropagation(W1, W2, Z1, Z2, X, t)
        W1, W2 = updateParams(W1, W2, dW1, dW2, alpha)
        print("Hallo")
        print(loss(X, t, W1, W2))
    return W1, W2

In [19]:
W1, W2 = gradientDescent(X_train, t_train, W1, W2, 10000, 0.0001)

[[-1027.4823657     -2.21533371]]
[[71.83644778 37.77105607]
 [ 7.04362225  3.33238166]]
Hallo
2777.658294459379
[[-1005.75681377    -2.15751606]]
[[66.81868323 35.04913117]
 [ 6.86157405  3.2433356 ]]
Hallo
2677.0176912293587
[[-984.55102067   -2.1015366 ]]
[[61.4135255  32.13706139]
 [ 6.68543847  3.15718367]]
Hallo
2580.638567066183
[[-963.86003229   -2.04732245]]
[[55.65977987 29.0566472 ]
 [ 6.51497468  3.07380827]]
Hallo
2488.3304298518806
[[-943.67780383   -1.99480242]]
[[49.6087578  25.83594972]
 [ 6.34994847  2.99309483]]
Hallo
2399.9081739751164
[[-923.99688756   -1.94390683]]
[[43.32343745 22.50877929]
 [ 6.19013159  2.91493147]]
Hallo
2315.192249711944
[[-904.80818472   -1.89456745]]
[[36.8767739  19.11375727]
 [ 6.0353015   2.83920895]]
Hallo
2234.008995422729
[[-886.10079272   -1.84671759]]
[[30.34920364 15.69298099]
 [ 5.88524154  2.76582073]]
Hallo
2156.19109381065
[[-867.86197178   -1.80029225]]
[[23.82548975 12.29037245]
 [ 5.73974134  2.69466323]]
Hallo
2081.57809577

181.96861250044793
[[-7.53960726e+01 -3.20155966e-02]]
[[-2.81044470e+01  7.27353760e+01]
 [ 2.35010070e-01  4.08232346e-02]]
Hallo
180.7934593713343
[[-7.51655726e+01 -3.10920082e-02]]
[[-2.81707336e+01  7.25782984e+01]
 [ 2.31810496e-01  3.97078137e-02]]
Hallo
179.62372678354487
[[-7.49318100e+01 -3.01642793e-02]]
[[-2.82309150e+01  7.24147402e+01]
 [ 2.28599120e-01  3.85863324e-02]]
Hallo
178.4595744100762
[[-7.46948309e+01 -2.92325879e-02]]
[[-2.82851179e+01  7.22448539e+01]
 [ 2.25376513e-01  3.74590204e-02]]
Hallo
177.30115742847417
[[-7.44546832e+01 -2.82971124e-02]]
[[-2.83334679e+01  7.20687924e+01]
 [ 2.22143249e-01  3.63261081e-02]]
Hallo
176.1486264712647
[[-7.42114161e+01 -2.73580310e-02]]
[[-2.83760904e+01  7.18867083e+01]
 [ 2.18899899e-01  3.51878268e-02]]
Hallo
175.00212758447762
[[-7.39650805e+01 -2.64155219e-02]]
[[-2.84131098e+01  7.16987539e+01]
 [ 2.15647034e-01  3.40444077e-02]]
Hallo
173.86180219400995
[[-7.37157288e+01 -2.54697628e-02]]
[[-2.84446497e+01  7.150

76.53593406794738
[[-21.49382315   0.11421117]]
[[-10.39930684  22.38951923]
 [ -0.26057734  -0.13994843]]
Hallo
76.42915395068074
[[-21.33142067   0.1145785 ]]
[[-10.33334384  22.24374613]
 [ -0.26181689  -0.14040048]]
Hallo
76.32385147823915
[[-21.1701091    0.11494332]]
[[-10.26785033  22.09900638]
 [ -0.26304797  -0.1408494 ]]
Hallo
76.22000617440338
[[-21.00988249   0.11530565]]
[[-10.20282351  21.9552933 ]
 [ -0.26427065  -0.14129521]]
Hallo
76.11759783593789
[[-20.85073489   0.11566552]]
[[-10.13826059  21.81260022]
 [ -0.26548499  -0.14173794]]
Hallo
76.016606529397
[[-20.69266037   0.11602294]]
[[-10.07415876  21.6709205 ]
 [ -0.26669106  -0.14217761]]
Hallo
75.91701258795185
[[-20.53565296   0.11637792]]
[[-10.01051521  21.53024751]
 [ -0.2678889   -0.14261425]]
Hallo
75.81879660823896
[[-20.37970671   0.1167305 ]]
[[-9.94732713 21.39057466]
 [-0.26907859 -0.14304788]]
Hallo
75.72193944723023
[[-20.22481567   0.11708068]]
[[-9.88459171 21.25189536]
 [-0.2702602  -0.14347852]]

 [-0.41017825 -0.19478448]]
Hallo
69.04792171223124
[[-2.9998236   0.15899861]]
[[-3.05007506  6.0052599 ]
 [-0.41051584 -0.19491248]]
Hallo
69.04247772172003
[[-2.96710624  0.15910172]]
[[-3.0370702   5.97591485]
 [-0.41085194 -0.19503997]]
Hallo
69.03709607922687
[[-2.93462484  0.15920441]]
[[-3.02415414  5.9467703 ]
 [-0.41118657 -0.19516695]]
Hallo
69.03177593705533
[[-2.90237774  0.15930669]]
[[-3.01132622  5.91782482]
 [-0.41151974 -0.19529344]]
Hallo
69.02651645933625
[[-2.87036329  0.15940855]]
[[-2.99858579  5.88907694]
 [-0.41185146 -0.19541944]]
Hallo
69.0213168218611
[[-2.83857988  0.15951   ]]
[[-2.98593219  5.86052525]
 [-0.41218175 -0.19554494]]
Hallo
69.01617621191734
[[-2.80702588  0.15961104]]
[[-2.97336478  5.83216832]
 [-0.41251061 -0.19566996]]
Hallo
69.0110938281267
[[-2.77569968  0.15971168]]
[[-2.96088291  5.80400475]
 [-0.41283805 -0.19579449]]
Hallo
69.00606888028537
[[-2.7445997   0.15981192]]
[[-2.94848595  5.77603313]
 [-0.41316409 -0.19591855]]
Hallo
69.00

[[0.45981757 0.17452357]]
[[-1.58235459  2.72107903]
 [-0.45961085 -0.21437945]]
Hallo
68.56186121931684
[[0.46679596 0.17458355]]
[[-1.5787654   2.71328254]
 [-0.45979368 -0.21445594]]
Hallo
68.56082636721509
[[0.47371745 0.17464346]]
[[-1.57519638  2.70553297]
 [-0.4599762  -0.21453233]]
Hallo
68.55979615440863
[[0.48058243 0.17470328]]
[[-1.57164739  2.69783001]
 [-0.46015842 -0.21460863]]
Hallo
68.5587705309437
[[0.48739129 0.17476302]]
[[-1.56811829  2.69017333]
 [-0.46034035 -0.21468484]]
Hallo
68.55774944753516
[[0.49414443 0.17482269]]
[[-1.56460893  2.68256259]
 [-0.46052198 -0.21476096]]
Hallo
68.55673285555726
[[0.50084223 0.17488227]]
[[-1.56111919  2.6749975 ]
 [-0.46070333 -0.21483698]]
Hallo
68.55572070703461
[[0.50748508 0.17494178]]
[[-1.55764891  2.66747772]
 [-0.46088438 -0.21491292]]
Hallo
68.55471295463312
[[0.51407336 0.17500121]]
[[-1.55419797  2.66000294]
 [-0.46106514 -0.21498877]]
Hallo
68.5537095516513
[[0.52060744 0.17506056]]
[[-1.55076623  2.65257285]
 [-0

[[1.04479909 0.18298847]]
[[-1.20656886  1.93127364]
 [-0.48495069 -0.22526194]]
Hallo
68.43978335080065
[[1.04645903 0.18304234]]
[[-1.20487012  1.92788667]
 [-0.48510951 -0.22533169]]
Hallo
68.43912537209951
[[1.04809937 0.18309619]]
[[-1.2031785   1.92451629]
 [-0.48526829 -0.22540142]]
Hallo
68.438468733216
[[1.04972024 0.18315004]]
[[-1.20149395  1.9211624 ]
 [-0.48542701 -0.22547115]]
Hallo
68.43781342684292
[[1.0513218  0.18320388]]
[[-1.19981642  1.91782487]
 [-0.48558568 -0.22554087]]
Hallo
68.43715944575641
[[1.05290418 0.18325772]]
[[-1.19814587  1.91450359]
 [-0.4857443  -0.22561058]]
Hallo
68.43650678281492
[[1.05446751 0.18331154]]
[[-1.19648225  1.91119847]
 [-0.48590287 -0.22568029]]
Hallo
68.43585543095809
[[1.05601194 0.18336535]]
[[-1.1948255   1.90790938]
 [-0.4860614  -0.22574999]]
Hallo
68.4352053832055
[[1.05753759 0.18341916]]
[[-1.1931756   1.90463623]
 [-0.48621987 -0.22581968]]
Hallo
68.43455663265595
[[1.05904461 0.18347295]]
[[-1.19153249  1.9013789 ]
 [-0.

 [-0.52568385 -0.24347564]]
Hallo
68.30372137009117
[[1.09572662 0.19702149]]
[[-0.91553752  1.39629664]
 [-0.5258501  -0.24355077]]
Hallo
68.30328521279553
[[1.09515088 0.19707891]]
[[-0.91473794  1.39496889]
 [-0.52601643 -0.24362594]]
Hallo
68.30284967487722
[[1.09457258 0.19713635]]
[[-0.91393986  1.39364437]
 [-0.52618285 -0.24370116]]
Hallo
68.30241475515622
[[1.09399174 0.19719382]]
[[-0.91314327  1.39232307]
 [-0.52634935 -0.24377642]]
Hallo
68.30198045245616
[[1.09340839 0.19725132]]
[[-0.91234817  1.39100496]
 [-0.52651593 -0.24385171]]
Hallo
68.30154676560444
[[1.09282256 0.19730886]]
[[-0.91155453  1.38969003]
 [-0.52668259 -0.24392705]]
Hallo
68.30111369343207
[[1.09223426 0.19736642]]
[[-0.91076237  1.38837827]
 [-0.52684934 -0.24400243]]
Hallo
68.3006812347736
[[1.09164352 0.19742401]]
[[-0.90997167  1.38706964]
 [-0.52701617 -0.24407785]]
Hallo
68.30024938846722
[[1.09105036 0.19748163]]
[[-0.90918242  1.38576414]
 [-0.52718309 -0.24415331]]
Hallo
68.2998181533547
[[1.0

[[0.94257256 0.21003034]]
[[-0.77014558  1.16506727]
 [-0.5635146  -0.26062682]]
Hallo
68.22283361766644
[[0.94179919 0.21009559]]
[[-0.76955086  1.16415368]
 [-0.56370355 -0.26071264]]
Hallo
68.222507290825
[[0.94102588 0.21016087]]
[[-0.76895676  1.16324122]
 [-0.56389262 -0.26079853]]
Hallo
68.22218138462043
[[0.94025262 0.21022621]]
[[-0.76836328  1.1623299 ]
 [-0.56408182 -0.26088447]]
Hallo
68.22185589829722
[[0.93947944 0.21029158]]
[[-0.76777043  1.1614197 ]
 [-0.56427115 -0.26097047]]
Hallo
68.221530831101
[[0.93870633 0.210357  ]]
[[-0.76717819  1.16051063]
 [-0.5644606  -0.26105653]]
Hallo
68.22120618227868
[[0.93793329 0.21042246]]
[[-0.76658657  1.15960268]
 [-0.56465019 -0.26114265]]
Hallo
68.22088195107834
[[0.93716034 0.21048796]]
[[-0.76599556  1.15869584]
 [-0.56483989 -0.26122882]]
Hallo
68.2205581367492
[[0.93638747 0.21055351]]
[[-0.76540516  1.15779011]
 [-0.56502973 -0.26131506]]
Hallo
68.22023473854178
[[0.93561469 0.2106191 ]]
[[-0.76481538  1.1568855 ]
 [-0.56

68.16146253089084
[[0.78302722 0.225137  ]]
[[-0.65436483  0.9895584 ]
 [-0.60731094 -0.28053551]]
Hallo
68.16121072516343
[[0.78233295 0.22521276]]
[[-0.6538751   0.98882231]
 [-0.60753083 -0.28063551]]
Hallo
68.1609592019369
[[0.7816392  0.22528856]]
[[-0.65338577  0.98808685]
 [-0.60775087 -0.28073558]]
Hallo
68.160707960662
[[0.78094599 0.22536443]]
[[-0.65289683  0.987352  ]
 [-0.60797107 -0.28083572]]
Hallo
68.16045700079013
[[0.7802533  0.22544034]]
[[-0.6524083   0.98661778]
 [-0.60819144 -0.28093594]]
Hallo
68.16020632177364
[[0.77956115 0.22551631]]
[[-0.65192015  0.98588417]
 [-0.60841197 -0.28103623]]
Hallo
68.15995592306547
[[0.77886952 0.22559234]]
[[-0.6514324   0.98515119]
 [-0.60863266 -0.2811366 ]]
Hallo
68.1597058041196
[[0.77817843 0.22566842]]
[[-0.65094505  0.98441882]
 [-0.60885352 -0.28123704]]
Hallo
68.15945596439042
[[0.77748787 0.22574456]]
[[-0.65045808  0.98368707]
 [-0.60907453 -0.28133756]]
Hallo
68.1592064033334
[[0.77679783 0.22582076]]
[[-0.64997152  0

68.11687149058476
[[0.65730832 0.24111049]]
[[-0.5653871   0.85604672]
 [-0.65373323 -0.30165051]]
Hallo
68.11666543491248
[[0.65672012 0.24119822]]
[[-0.56496675  0.85541624]
 [-0.65398848 -0.30176662]]
Hallo
68.1164595672267
[[0.65613245 0.24128601]]
[[-0.56454672  0.85478623]
 [-0.65424394 -0.30188282]]
Hallo
68.11625388710468
[[0.65554531 0.24137387]]
[[-0.56412701  0.8541567 ]
 [-0.65449959 -0.30199911]]
Hallo
68.1160483941242
[[0.65495869 0.2414618 ]]
[[-0.56370762  0.85352764]
 [-0.65475545 -0.30211549]]
Hallo
68.11584308786361
[[0.6543726 0.2415498]]
[[-0.56328855  0.85289906]
 [-0.6550115  -0.30223197]]
Hallo
68.11563796790183
[[0.65378704 0.24163787]]
[[-0.5628698   0.85227095]
 [-0.65526776 -0.30234853]]
Hallo
68.11543303381815
[[0.653202   0.24172601]]
[[-0.56245136  0.85164331]
 [-0.65552422 -0.30246519]]
Hallo
68.1152282851925
[[0.65261749 0.24181421]]
[[-0.56203324  0.85101615]
 [-0.65578088 -0.30258194]]
Hallo
68.11502372160534
[[0.6520335  0.24190248]]
[[-0.56161544  0

[[0.55260974 0.25949735]]
[[-0.48951047  0.74212093]
 [-0.70729328 -0.32601305]]
Hallo
68.07976018915775
[[0.55211643 0.2595998 ]]
[[-0.48914739  0.74157499]
 [-0.70759202 -0.32614893]]
Hallo
68.07958336945588
[[0.55162356 0.25970233]]
[[-0.48878459  0.74102945]
 [-0.70789101 -0.32628492]]
Hallo
68.07940666391085
[[0.55113114 0.25980495]]
[[-0.48842206  0.74048431]
 [-0.70819026 -0.32642103]]
Hallo
68.079230072182
[[0.55063917 0.25990765]]
[[-0.4880598   0.73993958]
 [-0.70848975 -0.32655725]]
Hallo
68.07905359392899
[[0.55014764 0.26001044]]
[[-0.48769781  0.73939524]
 [-0.7087895  -0.32669358]]
Hallo
68.07887722881183
[[0.54965655 0.26011332]]
[[-0.4873361   0.73885131]
 [-0.70908949 -0.32683003]]
Hallo
68.07870097649078
[[0.54916591 0.26021628]]
[[-0.48697466  0.73830777]
 [-0.70938974 -0.32696659]]
Hallo
68.07852483662647
[[0.54867572 0.26031932]]
[[-0.48661349  0.73776464]
 [-0.70969024 -0.32710327]]
Hallo
68.07834880887977
[[0.54818597 0.26042245]]
[[-0.48625259  0.7372219 ]
 [-0

68.0395426949423
[[0.44481016 0.28714901]]
[[-0.40886278  0.62059494]
 [-0.78802123 -0.36272401]]
Hallo
68.03938418834812
[[0.44441232 0.28727546]]
[[-0.40856055  0.62013843]
 [-0.78839076 -0.36289201]]
Hallo
68.03922572069644
[[0.44401482 0.28740202]]
[[-0.40825856  0.61968225]
 [-0.78876063 -0.36306017]]
Hallo
68.0390672916976
[[0.44361767 0.2875287 ]]
[[-0.4079568   0.61922642]
 [-0.78913083 -0.36322848]]
Hallo
68.03890890106211
[[0.44322085 0.28765549]]
[[-0.40765526  0.61877092]
 [-0.78950138 -0.36339695]]
Hallo
68.03875054850063
[[0.44282437 0.2877824 ]]
[[-0.40735396  0.61831575]
 [-0.78987226 -0.36356557]]
Hallo
68.03859223372379
[[0.44242823 0.28790943]]
[[-0.40705288  0.61786093]
 [-0.79024348 -0.36373434]]
Hallo
68.03843395644243
[[0.44203243 0.28803657]]
[[-0.40675203  0.61740643]
 [-0.79061505 -0.36390327]]
Hallo
68.03827571636742
[[0.44163697 0.28816382]]
[[-0.40645141  0.61695228]
 [-0.79098695 -0.36407236]]
Hallo
68.03811751320976
[[0.44124184 0.2882912 ]]
[[-0.40615102

 [-0.87740882 -0.4033521 ]]
Hallo
68.00526504955559
[[0.36513913 0.31787185]]
[[-0.34787807  0.52827586]
 [-0.87786399 -0.40355891]]
Hallo
68.00510824681065
[[0.36480666 0.31802758]]
[[-0.34762239  0.52788786]
 [-0.87831961 -0.40376594]]
Hallo
68.00495142039131
[[0.36447444 0.31818347]]
[[-0.3473669   0.52750015]
 [-0.87877569 -0.40397317]]
Hallo
68.00479457000752
[[0.36414249 0.31833952]]
[[-0.3471116   0.52711273]
 [-0.87923223 -0.40418061]]
Hallo
68.00463769536918
[[0.36381078 0.31849572]]
[[-0.3468565   0.5267256 ]
 [-0.87968923 -0.40438825]]
Hallo
68.004480796186
[[0.36347934 0.31865207]]
[[-0.3466016   0.52633876]
 [-0.88014668 -0.4045961 ]]
Hallo
68.00432387216763
[[0.36314815 0.31880859]]
[[-0.3463469   0.52595221]
 [-0.88060459 -0.40480416]]
Hallo
68.00416692302358
[[0.36281722 0.31896525]]
[[-0.34609239  0.52556595]
 [-0.88106296 -0.40501243]]
Hallo
68.00400994846323
[[0.36248655 0.31912208]]
[[-0.34583807  0.52517998]
 [-0.88152179 -0.40522091]]
Hallo
68.00385294819588
[[0.3

Hallo
67.97169952293754
[[0.30102583 0.3539805 ]]
[[-0.29874091  0.45352949]
 [-0.98351561 -0.45154567]]
Hallo
67.97153129589485
[[0.30073961 0.35417414]]
[[-0.29852343  0.45319774]
 [-0.98408213 -0.45180288]]
Hallo
67.97136298064355
[[0.30045357 0.354368  ]]
[[-0.29830613  0.45286623]
 [-0.98464928 -0.45206037]]
Hallo
67.97119457684346
[[0.30016772 0.35456208]]
[[-0.298089    0.45253498]
 [-0.98521705 -0.45231815]]
Hallo
67.97102608415386
[[0.29988206 0.35475637]]
[[-0.29787204  0.45220398]
 [-0.98578544 -0.45257621]]
Hallo
67.97085750223377
[[0.29959658 0.35495087]]
[[-0.29765526  0.45187323]
 [-0.98635446 -0.45283455]]
Hallo
67.97068883074164
[[0.29931129 0.35514559]]
[[-0.29743864  0.45154273]
 [-0.98692411 -0.45309317]]
Hallo
67.97052006933568
[[0.29902618 0.35534052]]
[[-0.2972222   0.45121248]
 [-0.98749438 -0.45335208]]
Hallo
67.97035121767362
[[0.29874126 0.35553567]]
[[-0.29700592  0.45088248]
 [-0.98806528 -0.45361127]]
Hallo
67.97018227541284
[[0.29845653 0.35573103]]
[[-0.

 [-1.11923733 -0.51313464]]
Hallo
67.93329641118741
[[0.24375086 0.40065549]]
[[-0.25613556  0.38830652]
 [-1.11996105 -0.51346288]]
Hallo
67.93310093975987
[[0.24349683 0.40090362]]
[[-0.25595246  0.38802498]
 [-1.12068564 -0.51379153]]
Hallo
67.93290529582036
[[0.24324292 0.40115207]]
[[-0.25576951  0.38774366]
 [-1.12141111 -0.51412057]]
Hallo
67.93270947890038
[[0.24298913 0.40140081]]
[[-0.25558671  0.38746256]
 [-1.12213748 -0.51445001]]
Hallo
67.93251348853062
[[0.24273544 0.40164987]]
[[-0.25540407  0.38718169]
 [-1.12286472 -0.51477985]]
Hallo
67.93231732424076
[[0.24248187 0.40189923]]
[[-0.25522157  0.38690103]
 [-1.12359285 -0.5151101 ]]
Hallo
67.93212098555972
[[0.24222841 0.4021489 ]]
[[-0.25503923  0.38662059]
 [-1.12432188 -0.51544074]]
Hallo
67.93192447201558
[[0.24197506 0.40239888]]
[[-0.25485704  0.38634038]
 [-1.12505179 -0.51577179]]
Hallo
67.93172778313546
[[0.24172182 0.40264916]]
[[-0.254675    0.38606038]
 [-1.12578259 -0.51610323]]
Hallo
67.93153091844563
[[0

67.87896495385583
[[0.18393226 0.47212657]]
[[-0.21568418  0.3256564 ]
 [-1.3281085  -0.60779989]]
Hallo
67.87871061354987
[[0.18369358 0.47246964]]
[[-0.21553677  0.32542574]
 [-1.32910433 -0.60825091]]
Hallo
67.87845595132622
[[0.18345492 0.47281319]]
[[-0.2153895   0.32519529]
 [-1.33010155 -0.60870254]]
Hallo
67.87820096638751
[[0.18321625 0.47315723]]
[[-0.21524237  0.32496502]
 [-1.33110016 -0.6091548 ]]
Hallo
67.87794565793426
[[0.18297759 0.47350177]]
[[-0.21509539  0.32473496]
 [-1.33210014 -0.60960768]]
Hallo
67.87769002516511
[[0.18273893 0.47384679]]
[[-0.21494855  0.32450509]
 [-1.33310152 -0.61006119]]
Hallo
67.87743406727658
[[0.18250027 0.47419231]]
[[-0.21480185  0.32427542]
 [-1.33410428 -0.61051532]]
Hallo
67.87717778346331
[[0.18226161 0.47453831]]
[[-0.21465529  0.32404595]
 [-1.33510844 -0.61097008]]
Hallo
67.87692117291787
[[0.18202295 0.47488482]]
[[-0.21450887  0.32381667]
 [-1.336114   -0.61142547]]
Hallo
67.87666423483087
[[0.18178429 0.47523181]]
[[-0.214362

[[0.13239187 0.55757446]]
[[-0.18762874  0.28110693]
 [-1.57484269 -0.71945832]]
Hallo
67.81606371794648
[[0.13213853 0.55804809]]
[[-0.18751195  0.28091741]
 [-1.57620213 -0.72007307]]
Hallo
67.81571899348513
[[0.13188503 0.5585225 ]]
[[-0.18739532  0.28072808]
 [-1.57756368 -0.72068878]]
Hallo
67.81537371928536
[[0.13163136 0.55899769]]
[[-0.18727884  0.28053895]
 [-1.57892736 -0.72130544]]
Hallo
67.81502789392526
[[0.13137754 0.55947364]]
[[-0.18716251  0.28035001]
 [-1.58029317 -0.72192305]]
Hallo
67.8146815159787
[[0.13112355 0.55995038]]
[[-0.18704634  0.28016127]
 [-1.5816611  -0.72254162]]
Hallo
67.81433458401546
[[0.1308694 0.5604279]]
[[-0.18693031  0.27997273]
 [-1.58303117 -0.72316116]]
Hallo
67.81398709660098
[[0.13061509 0.5609062 ]]
[[-0.18681444  0.27978438]
 [-1.58440338 -0.72378165]]
Hallo
67.8136390522965
[[0.1303606  0.56138528]]
[[-0.18669872  0.27959622]
 [-1.58577773 -0.72440311]]
Hallo
67.81329044965908
[[0.13010595 0.56186514]]
[[-0.18658315  0.27940826]
 [-1.5

67.7393211748585
[[0.07995018 0.66374443]]
[[-0.16835313  0.24870788]
 [-1.87678916 -0.85589242]]
Hallo
67.73884174321752
[[0.07964198 0.66440357]]
[[-0.16826857  0.24855748]
 [-1.87864457 -0.85673016]]
Hallo
67.73836139837914
[[0.07933333 0.66506394]]
[[-0.1681842   0.2484073 ]
 [-1.88050316 -0.85756933]]
Hallo
67.73788013778153
[[0.07902422 0.66572553]]
[[-0.16810004  0.24825735]
 [-1.88236496 -0.85840993]]
Hallo
67.73739795885444
[[0.07871465 0.66638836]]
[[-0.16801607  0.24810762]
 [-1.88422996 -0.85925197]]
Hallo
67.7369148590192
[[0.07840462 0.66705242]]
[[-0.1679323   0.24795812]
 [-1.88609817 -0.86009546]]
Hallo
67.73643083568864
[[0.07809412 0.66771771]]
[[-0.16784872  0.24780884]
 [-1.88796959 -0.86094039]]
Hallo
67.73594588626712
[[0.07778316 0.66838425]]
[[-0.16776535  0.24765979]
 [-1.88984425 -0.86178677]]
Hallo
67.73546000815041
[[0.07747172 0.66905203]]
[[-0.16768217  0.24751097]
 [-1.89172213 -0.8626346 ]]
Hallo
67.73497319872583
[[0.07715982 0.66972106]]
[[-0.16759919

67.60413150385048
[[-0.00538525  0.84786928]]
[[-0.15537165  0.22151173]
 [-2.38375502 -1.08456232]]
Hallo
67.6033659956821
[[-0.00587476  0.84889992]]
[[-0.15534636  0.22142353]
 [-2.38652133 -1.085809  ]]
Hallo
67.60259872523729
[[-0.0063656   0.84993278]]
[[-0.15532145  0.22133569]
 [-2.38929273 -1.08705797]]
Hallo
67.60182968707596
[[-0.00685777  0.85096788]]
[[-0.1552969   0.22124821]
 [-2.39206921 -1.08830922]]
Hallo
67.60105887573958
[[-0.00735127  0.8520052 ]]
[[-0.15527273  0.2211611 ]
 [-2.3948508  -1.08956276]]
Hallo
67.60028628575124
[[-0.00784612  0.85304477]]
[[-0.15524893  0.22107435]
 [-2.3976375  -1.0908186 ]]
Hallo
67.59951191161538
[[-0.00834232  0.85408658]]
[[-0.15522551  0.22098798]
 [-2.40042933 -1.09207673]]
Hallo
67.59873574781794
[[-0.00883988  0.85513065]]
[[-0.15520247  0.22090197]
 [-2.40322628 -1.09333716]]
Hallo
67.59795778882618
[[-0.0093388   0.85617698]]
[[-0.1551798   0.22081633]
 [-2.40602837 -1.0945999 ]]
Hallo
67.59717802908875
[[-0.00983909  0.857

67.36434856237949
[[-0.17359397  1.16283625]]
[[-0.16345898  0.21411933]
 [-3.18120009 -1.44370605]]
Hallo
67.36298174096711
[[-0.174659    1.16458405]]
[[-0.16357764  0.2141648 ]
 [-3.18531408 -1.44555861]]
Hallo
67.36161131284301
[[-0.17572821  1.16633589]]
[[-0.16369728  0.21421116]
 [-3.18943361 -1.44741367]]
Hallo
67.36023726765814
[[-0.17680162  1.16809179]]
[[-0.16381791  0.21425842]
 [-3.19355869 -1.44927124]]
Hallo
67.35885959505048
[[-0.17787925  1.16985175]]
[[-0.16393953  0.21430659]
 [-3.19768929 -1.4511313 ]]
Hallo
67.35747828464503
[[-0.17896112  1.17161578]]
[[-0.16406214  0.21435567]
 [-3.20182539 -1.45299386]]
Hallo
67.35609332605429
[[-0.18004726  1.17338389]]
[[-0.16418576  0.21440565]
 [-3.20596698 -1.4548589 ]]
Hallo
67.35470470887849
[[-0.18113769  1.17515609]]
[[-0.16431038  0.21445656]
 [-3.21011403 -1.4567264 ]]
Hallo
67.35331242270581
[[-0.18223243  1.17693238]]
[[-0.16443601  0.21450839]
 [-3.21426653 -1.45859638]]
Hallo
67.3519164571127
[[-0.18333149  1.178

 [-4.17166444 -1.89120861]]
Hallo
66.93535941643377
[[-0.58162312  1.68104908]]
[[-0.22621869  0.25848603]
 [-4.17536682 -1.89289837]]
Hallo
66.93292827045401
[[-0.5843845   1.68379212]]
[[-0.22668426  0.25888098]
 [-4.17905165 -1.8945805 ]]
Hallo
66.93049212462759
[[-0.58715685  1.68653832]]
[[-0.22715162  0.25927815]
 [-4.1827187  -1.89625489]]
Hallo
66.92805098789628
[[-0.58994018  1.68928764]]
[[-0.22762076  0.25967754]
 [-4.18636773 -1.89792144]]
Hallo
66.92560486946888
[[-0.59273453  1.69204005]]
[[-0.22809169  0.26007917]
 [-4.18999851 -1.89958004]]
Hallo
66.9231537788235
[[-0.59553991  1.69479553]]
[[-0.2285644   0.26048303]
 [-4.1936108  -1.90123059]]
Hallo
66.9206977257095
[[-0.59835636  1.69755403]]
[[-0.22903888  0.26088913]
 [-4.19720436 -1.90287299]]
Hallo
66.91823672014988
[[-0.60118389  1.70031552]]
[[-0.22951513  0.26129748]
 [-4.20077894 -1.90450712]]
Hallo
66.915770772443
[[-0.60402252  1.70307997]]
[[-0.22999315  0.26170807]
 [-4.20433431 -1.90613289]]
Hallo
66.9132

66.4048385163682
[[-1.30445171  2.20665939]]
[[-0.32907236  0.37168688]
 [-4.24214387 -1.93460813]]
Hallo
66.40198351920199
[[-1.30888876  2.20898972]]
[[-0.32948449  0.37237997]
 [-4.23756965 -1.93265162]]
Hallo
66.39913090425752
[[-1.31332525  2.2113114 ]]
[[-0.32989242  0.37307207]
 [-4.23293467 -1.93066808]]
Hallo
66.39628072759596
[[-1.31776097  2.21362438]]
[[-0.33029608  0.37376314]
 [-4.22823897 -1.92865752]]
Hallo
66.39343304512728
[[-1.32219575  2.2159286 ]]
[[-0.33069543  0.37445312]
 [-4.22348262 -1.92661996]]
Hallo
66.39058791260244
[[-1.3266294   2.21822401]]
[[-0.33109042  0.37514197]
 [-4.21866565 -1.92455542]]
Hallo
66.38774538560598
[[-1.33106174  2.22051056]]
[[-0.33148099  0.37582962]
 [-4.21378814 -1.92246391]]
Hallo
66.38490551954843
[[-1.33549259  2.2227882 ]]
[[-0.33186709  0.37651603]
 [-4.20885015 -1.92034548]]
Hallo
66.38206836965873
[[-1.33992174  2.22505687]]
[[-0.33224867  0.37720114]
 [-4.20385176 -1.91820013]]
Hallo
66.37923399097673
[[-1.34434902  2.227

[[-1.9443028   2.49233081]]
[[-0.27742472  0.41123347]
 [-2.40562924 -1.1240909 ]]
Hallo
65.91168385380566
[[-1.94499514  2.49293692]]
[[-0.27652797  0.41060965]
 [-2.39592888 -1.1197187 ]]
Hallo
65.90996143669884
[[-1.94566281  2.49353955]]
[[-0.27562733  0.40997741]
 [-2.38624969 -1.11535494]]
Hallo
65.90824415931044
[[-1.94630588  2.49413876]]
[[-0.27472283  0.40933678]
 [-2.37659195 -1.11099974]]
Hallo
65.90653199875992
[[-1.94692444  2.49473458]]
[[-0.27381452  0.40868778]
 [-2.36695592 -1.10665322]]
Hallo
65.90482493210504
[[-1.94751856  2.49532708]]
[[-0.27290246  0.40803045]
 [-2.35734188 -1.10231552]]
Hallo
65.90312293634526
[[-1.94808832  2.4959163 ]]
[[-0.2719867   0.40736482]
 [-2.34775009 -1.09798674]]
Hallo
65.90142598842542
[[-1.9486338   2.49650229]]
[[-0.27106729  0.40669092]
 [-2.33818079 -1.093667  ]]
Hallo
65.89973406523961
[[-1.94915508  2.49708509]]
[[-0.27014428  0.40600877]
 [-2.32863426 -1.08935643]]
Hallo
65.89804714363454
[[-1.94965226  2.49766476]]
[[-0.2692

65.5920357567685
[[-1.65053629  2.6018927 ]]
[[-0.03443096  0.11551747]
 [-0.84133835 -0.39589513]]
Hallo
65.59099872979333
[[-1.64858695  2.60226636]]
[[-0.03360605  0.1142075 ]
 [-0.83796517 -0.39423965]]
Hallo
65.58996288258136
[[-1.64663837  2.60263946]]
[[-0.0327833   0.11289942]
 [-0.83460835 -0.39259158]]
Hallo
65.58892820772834
[[-1.64469058  2.603012  ]]
[[-0.0319627   0.11159326]
 [-0.83126782 -0.39095089]]
Hallo
65.5878946978774
[[-1.64274363  2.60338396]]
[[-0.03114427  0.11028904]
 [-0.82794349 -0.38931755]]
Hallo
65.58686234571894
[[-1.64079757  2.60375534]]
[[-0.03032799  0.10898678]
 [-0.82463526 -0.38769151]]
Hallo
65.58583114399029
[[-1.63885244  2.60412615]]
[[-0.02951387  0.10768648]
 [-0.82134305 -0.38607274]]
Hallo
65.58480108547523
[[-1.63690829  2.60449638]]
[[-0.02870191  0.10638818]
 [-0.81806677 -0.3844612 ]]
Hallo
65.5837721630039
[[-1.63496515  2.60486603]]
[[-0.02789211  0.10509188]
 [-0.81480633 -0.38285685]]
Hallo
65.58274436945258
[[-1.63302308  2.60523

65.37748347043373
[[-1.27577935  2.66914549]]
[[ 0.1010222  -0.11677972]
 [-0.36606782 -0.15540888]]
Hallo
65.37659014943402
[[-1.27449806  2.66936379]]
[[ 0.10142372 -0.11751083]
 [-0.3648242  -0.15475853]]
Hallo
65.37569712403901
[[-1.27322012  2.66958143]]
[[ 0.10182381 -0.11823953]
 [-0.36358553 -0.15411066]]
Hallo
65.37480439252724
[[-1.2719455   2.66979842]]
[[ 0.10222246 -0.11896582]
 [-0.36235179 -0.15346526]]
Hallo
65.37391195318851
[[-1.27067422  2.67001477]]
[[ 0.10261968 -0.11968973]
 [-0.36112296 -0.15282232]]
Hallo
65.37301980432363
[[-1.26940627  2.67023046]]
[[ 0.10301548 -0.12041124]
 [-0.35989902 -0.15218184]]
Hallo
65.37212794424445
[[-1.26814164  2.6704455 ]]
[[ 0.10340985 -0.12113036]
 [-0.35867994 -0.15154381]]
Hallo
65.37123637127368
[[-1.26688032  2.6706599 ]]
[[ 0.10380281 -0.1218471 ]
 [-0.3574657  -0.1509082 ]]
Hallo
65.37034508374501
[[-1.26562232  2.67087366]]
[[ 0.10419435 -0.12256147]
 [-0.35625627 -0.15027502]]
Hallo
65.3694540800028
[[-1.26436762  2.671

65.20301219017854
[[-1.07804184  2.7014737 ]]
[[ 0.15750896 -0.22189206]
 [-0.19226972 -0.06374603]]
Hallo
65.20215469478778
[[-1.07730566  2.70158659]]
[[ 0.157693   -0.22224386]
 [-0.19168561 -0.06343718]]
Hallo
65.20129730188395
[[-1.07657157  2.70169908]]
[[ 0.15787627 -0.22259425]
 [-0.1911036  -0.06312947]]
Hallo
65.20044001099923
[[-1.07583956  2.70181117]]
[[ 0.15805874 -0.22294323]
 [-0.19052369 -0.06282289]]
Hallo
65.1995828216688
[[-1.07510963  2.70192286]]
[[ 0.15824044 -0.22329081]
 [-0.18994587 -0.06251743]]
Hallo
65.19872573343088
[[-1.07438177  2.70203415]]
[[ 0.15842137 -0.223637  ]
 [-0.18937014 -0.0622131 ]]
Hallo
65.19786874582664
[[-1.07365597  2.70214503]]
[[ 0.15860151 -0.22398179]
 [-0.18879648 -0.06190988]]
Hallo
65.19701185840027
[[-1.07293223  2.70225552]]
[[ 0.15878089 -0.22432519]
 [-0.18822488 -0.06160778]]
Hallo
65.19615507069896
[[-1.07221055  2.70236561]]
[[ 0.1589595  -0.22466721]
 [-0.18765534 -0.06130678]]
Hallo
65.19529838227268
[[-1.07149091  2.702

 [-0.10696791 -0.01927596]]
Hallo
65.02803377394639
[[-0.96293055  2.71762992]]
[[ 0.18197884 -0.27003714]
 [-0.1066826  -0.01913193]]
Hallo
65.02719073311165
[[-0.9625179   2.71767975]]
[[ 0.18204509 -0.27017519]
 [-0.10639825 -0.01898844]]
Hallo
65.02634774134951
[[-0.96210639  2.71772936]]
[[ 0.18211093 -0.27031251]
 [-0.10611485 -0.01884551]]
Hallo
65.02550479853558
[[-0.96169601  2.71777875]]
[[ 0.18217639 -0.27044911]
 [-0.10583242 -0.01870311]]
Hallo
65.02466190454615
[[-0.96128675  2.71782791]]
[[ 0.18224145 -0.27058499]
 [-0.10555093 -0.01856126]]
Hallo
65.02381905925843
[[-0.96087861  2.71787686]]
[[ 0.18230611 -0.27072014]
 [-0.1052704  -0.01841995]]
Hallo
65.0229762625503
[[-0.96047159  2.71792558]]
[[ 0.18237039 -0.27085459]
 [-0.1049908  -0.01827917]]
Hallo
65.0221335143005
[[-0.96006569  2.71797408]]
[[ 0.18243427 -0.27098831]
 [-0.10471215 -0.01813894]]
Hallo
65.02129081438845
[[-0.9596609   2.71802236]]
[[ 0.18249777 -0.27112133]
 [-0.10443444 -0.01799923]]
Hallo
65.02

 [-0.06072326  0.00260316]]
Hallo
64.83441161520578
[[-0.89171633  2.72433166]]
[[ 0.1890807  -0.28684032]
 [-0.06058794  0.00265948]]
Hallo
64.83357773883982
[[-0.89149113  2.72434389]]
[[ 0.18908422 -0.28686271]
 [-0.06045303  0.00271556]]
Hallo
64.83274389615107
[[-0.89126648  2.72435599]]
[[ 0.18908756 -0.28688478]
 [-0.06031854  0.00277139]]
Hallo
64.8319100871083
[[-0.89104239  2.72436799]]
[[ 0.18909074 -0.28690653]
 [-0.06018445  0.00282696]]
Hallo
64.83107631168055
[[-0.89081884  2.72437986]]
[[ 0.18909374 -0.28692796]
 [-0.06005078  0.00288229]]
Hallo
64.830242569837
[[-0.89059585  2.72439163]]
[[ 0.18909658 -0.28694907]
 [-0.05991751  0.00293737]]
Hallo
64.82940886154701
[[-0.8903734   2.72440328]]
[[ 0.18909924 -0.28696986]
 [-0.05978465  0.00299221]]
Hallo
64.82857518678014
[[-0.89015151  2.72441483]]
[[ 0.18910173 -0.28699034]
 [-0.05965219  0.0030468 ]]
Hallo
64.82774154550604
[[-0.88993015  2.72442626]]
[[ 0.18910406 -0.2870105 ]
 [-0.05952013  0.00310114]]
Hallo
64.826

64.67655199752492
[[-0.85722503  2.72492726]]
[[ 0.1872818  -0.28647081]
 [-0.04093165  0.00961659]]
Hallo
64.67572410788347
[[-0.85707987  2.72492271]]
[[ 0.18726214 -0.28644961]
 [-0.04085356  0.00963716]]
Hallo
64.67489624815278
[[-0.85693502  2.7249181 ]]
[[ 0.1872424  -0.28642826]
 [-0.04077567  0.0096576 ]]
Hallo
64.67406841832069
[[-0.85679048  2.72491342]]
[[ 0.18722257 -0.28640675]
 [-0.04069799  0.00967791]]
Hallo
64.67324061837515
[[-0.85664624  2.72490867]]
[[ 0.18720267 -0.28638509]
 [-0.04062053  0.00969808]]
Hallo
64.67241284830408
[[-0.85650232  2.72490385]]
[[ 0.18718269 -0.28636328]
 [-0.04054326  0.00971811]]
Hallo
64.67158510809557
[[-0.8563587   2.72489897]]
[[ 0.18716263 -0.28634132]
 [-0.04046621  0.00973801]]
Hallo
64.67075739773766
[[-0.85621539  2.72489403]]
[[ 0.18714249 -0.28631921]
 [-0.04038935  0.00975778]]
Hallo
64.66992971721845
[[-0.85607238  2.72488902]]
[[ 0.18712227 -0.28629695]
 [-0.04031271  0.00977741]]
Hallo
64.66910206652616
[[-0.85592968  2.72

64.505801960143
[[-0.83262515  2.7227918 ]]
[[ 0.18193089 -0.27960005]
 [-0.02830985  0.01150926]]
Hallo
64.50498006030806
[[-0.83252798  2.72277663]]
[[ 0.18190058 -0.27955803]
 [-0.02826244  0.01150904]]
Hallo
64.50415818863449
[[-0.83243098  2.72276142]]
[[ 0.18187025 -0.27951595]
 [-0.02821514  0.01150873]]
Hallo
64.50333634511628
[[-0.83233415  2.72274617]]
[[ 0.18183988 -0.27947381]
 [-0.02816793  0.01150836]]
Hallo
64.50251452974757
[[-0.83223748  2.72273088]]
[[ 0.18180949 -0.27943161]
 [-0.02812082  0.01150792]]
Hallo
64.50169274252237
[[-0.83214098  2.72271556]]
[[ 0.18177907 -0.27938935]
 [-0.02807382  0.0115074 ]]
Hallo
64.50087098343478
[[-0.83204464  2.72270019]]
[[ 0.18174862 -0.27934704]
 [-0.02802691  0.01150681]]
Hallo
64.50004925247893
[[-0.83194847  2.72268479]]
[[ 0.18171815 -0.27930467]
 [-0.0279801   0.01150615]]
Hallo
64.49922754964892
[[-0.83185247  2.72266935]]
[[ 0.18168765 -0.27926225]
 [-0.02793339  0.01150542]]
Hallo
64.4984058749389
[[-0.83175663  2.72265

 [-0.01995165  0.01008116]]
Hallo
64.32891675651173
[[-0.81485499  2.71875599]]
[[ 0.17496323 -0.26960553]
 [-0.01991949  0.01006919]]
Hallo
64.32810082127357
[[-0.81478503  2.71873432]]
[[ 0.17492993 -0.26955668]
 [-0.01988739  0.01005719]]
Hallo
64.3272849131701
[[-0.81471516  2.71871262]]
[[ 0.17489662 -0.26950782]
 [-0.01985533  0.01004514]]
Hallo
64.32646903219745
[[-0.81464538  2.7186909 ]]
[[ 0.17486332 -0.26945896]
 [-0.01982332  0.01003305]]
Hallo
64.32565317835176
[[-0.8145757   2.71866916]]
[[ 0.17483001 -0.26941008]
 [-0.01979135  0.01002092]]
Hallo
64.32483735162913
[[-0.8145061  2.7186474]]
[[ 0.1747967  -0.26936119]
 [-0.01975944  0.01000875]]
Hallo
64.32402155202567
[[-0.8144366   2.71862561]]
[[ 0.17476339 -0.26931229]
 [-0.01972757  0.00999654]]
Hallo
64.32320577953755
[[-0.81436719  2.7186038 ]]
[[ 0.17473008 -0.26926338]
 [-0.01969574  0.00998429]]
Hallo
64.3223900341609
[[-0.81429787  2.71858197]]
[[ 0.17469676 -0.26921447]
 [-0.01966397  0.00997201]]
Hallo
64.3215

64.12738687082697
[[-0.79980994  2.71278364]]
[[ 0.16678233 -0.25745719]
 [-0.01307675  0.00607041]]
Hallo
64.12657755745995
[[-0.79975689  2.71275751]]
[[ 0.16675016 -0.25740901]
 [-0.0130526   0.00605085]]
Hallo
64.12576827039545
[[-0.7997039   2.71273136]]
[[ 0.166718   -0.25736085]
 [-0.01302846  0.00603127]]
Hallo
64.12495900963037
[[-0.79965095  2.71270521]]
[[ 0.16668585 -0.25731269]
 [-0.01300434  0.00601167]]
Hallo
64.12414977516184
[[-0.79959805  2.71267903]]
[[ 0.16665371 -0.25726455]
 [-0.01298025  0.00599204]]
Hallo
64.12334056698694
[[-0.79954521  2.71265284]]
[[ 0.16662158 -0.25721643]
 [-0.01295617  0.0059724 ]]
Hallo
64.12253138510268
[[-0.79949241  2.71262664]]
[[ 0.16658945 -0.25716831]
 [-0.01293212  0.00595273]]
Hallo
64.12172222950618
[[-0.79943966  2.71260043]]
[[ 0.16655734 -0.25712021]
 [-0.01290808  0.00593303]]
Hallo
64.1209131001944
[[-0.79938696  2.7125742 ]]
[[ 0.16652524 -0.25707212]
 [-0.01288406  0.00591332]]
Hallo
64.12010399716456
[[-0.7993343   2.712

 [-0.00846711  0.00164064]]
Hallo
63.9612196315841
[[-0.78978574  2.70714076]]
[[ 0.16039037 -0.2478568 ]
 [-0.00844597  0.0016172 ]]
Hallo
63.960415677556135
[[-0.7897409   2.70711224]]
[[ 0.16036062 -0.24781203]
 [-0.00842483  0.00159374]]
Hallo
63.95961174926967
[[-0.78969609  2.70708371]]
[[ 0.16033087 -0.24776727]
 [-0.00840371  0.00157027]]
Hallo
63.958807846722046
[[-0.78965131  2.70705517]]
[[ 0.16030114 -0.24772254]
 [-0.00838259  0.00154679]]
Hallo
63.958003969910905
[[-0.78960657  2.70702662]]
[[ 0.16027142 -0.24767782]
 [-0.00836149  0.00152329]]
Hallo
63.957200118833626
[[-0.78956185  2.70699806]]
[[ 0.16024172 -0.24763312]
 [-0.00834039  0.00149977]]
Hallo
63.956396293487686
[[-0.78951717  2.70696949]]
[[ 0.16021203 -0.24758844]
 [-0.00831931  0.00147624]]
Hallo
63.955592493870604
[[-0.78947252  2.70694091]]
[[ 0.16018235 -0.24754378]
 [-0.00829823  0.00145269]]
Hallo
63.95478871997982
[[-0.7894279   2.70691232]]
[[ 0.16015268 -0.24749915]
 [-0.00827716  0.00142912]]
Hall

63.79534640401419
[[-0.78110188  2.70105139]]
[[ 0.15451888 -0.23902235]
 [-0.00424481 -0.00354068]]
Hallo
63.79454772661649
[[-0.78106251  2.70102116]]
[[ 0.15449195 -0.23898185]
 [-0.00422519 -0.00356694]]
Hallo
63.79374907446619
[[-0.78102316  2.70099092]]
[[ 0.15446503 -0.23894138]
 [-0.00420557 -0.0035932 ]]
Hallo
63.79295044756099
[[-0.78098383  2.70096068]]
[[ 0.15443812 -0.23890092]
 [-0.00418596 -0.00361948]]
Hallo
63.79215184589868
[[-0.78094452  2.70093043]]
[[ 0.15441122 -0.23886049]
 [-0.00416635 -0.00364578]]
Hallo
63.79135326947697
[[-0.78090523  2.70090017]]
[[ 0.15438434 -0.23882008]
 [-0.00414675 -0.00367208]]
Hallo
63.79055471829364
[[-0.78086597  2.7008699 ]]
[[ 0.15435748 -0.23877969]
 [-0.00412715 -0.00369839]]
Hallo
63.78975619234639
[[-0.78082672  2.70083963]]
[[ 0.15433062 -0.23873932]
 [-0.00410756 -0.00372472]]
Hallo
63.78895769163297
[[-0.7807875   2.70080935]]
[[ 0.15430379 -0.23869897]
 [-0.00408797 -0.00375106]]
Hallo
63.788159216151186
[[-0.7807483   2.7

63.632935905047766
[[-0.7734788   2.69475159]]
[[ 0.1493074  -0.23120185]
 [-0.00032642 -0.0091212 ]]
Hallo
63.63214233266226
[[-0.77344326  2.69472011]]
[[ 0.14928324 -0.23116568]
 [-0.00030754 -0.00914958]]
Hallo
63.6313487850824
[[-0.77340774  2.69468862]]
[[ 0.14925909 -0.23112953]
 [-0.00028867 -0.00917797]]
Hallo
63.630555262306125
[[-0.77337224  2.69465713]]
[[ 0.14923495 -0.2310934 ]
 [-0.0002698  -0.00920638]]
Hallo
63.62976176433132
[[-0.77333675  2.69462564]]
[[ 0.14921082 -0.23105729]
 [-0.00025093 -0.00923479]]
Hallo
63.62896829115589
[[-0.77330128  2.69459414]]
[[ 0.14918671 -0.2310212 ]
 [-0.00023207 -0.00926321]]
Hallo
63.628174842777796
[[-0.77326582  2.69456263]]
[[ 1.49162613e-01 -2.30985136e-01]
 [-2.13206891e-04 -9.29163915e-03]]
Hallo
63.627381419194954
[[-0.77323038  2.69453112]]
[[ 1.49138528e-01 -2.30949089e-01]
 [-1.94347471e-04 -9.32007879e-03]]
Hallo
63.62658802040524
[[-0.77319496  2.69449961]]
[[ 1.49114455e-01 -2.30913063e-01]
 [-1.75490547e-04 -9.3485276

[[-0.76476058  2.68644007]]
[[ 0.14347523 -0.22250913]
 [ 0.00449701 -0.01675971]]
Hallo
63.42743638233945
[[-0.76472863  2.68640743]]
[[ 0.14345431 -0.22247811]
 [ 0.00451544 -0.01679023]]
Hallo
63.426649191141586
[[-0.76469668  2.68637478]]
[[ 0.14343339 -0.2224471 ]
 [ 0.00453387 -0.01682076]]
Hallo
63.4258620242283
[[-0.76466475  2.68634214]]
[[ 0.1434125  -0.22241612]
 [ 0.0045523  -0.0168513 ]]
Hallo
63.425074881597666
[[-0.76463283  2.68630948]]
[[ 0.14339161 -0.22238515]
 [ 0.00457073 -0.01688185]]
Hallo
63.42428776324773
[[-0.76460092  2.68627683]]
[[ 0.14337073 -0.22235421]
 [ 0.00458916 -0.0169124 ]]
Hallo
63.42350066917656
[[-0.76456902  2.68624417]]
[[ 0.14334987 -0.22232328]
 [ 0.00460759 -0.01694296]]
Hallo
63.42271359938225
[[-0.76453713  2.6862115 ]]
[[ 0.14332902 -0.22229237]
 [ 0.00462602 -0.01697353]]
Hallo
63.42192655386283
[[-0.76450526  2.68617884]]
[[ 0.14330817 -0.22226148]
 [ 0.00464444 -0.0170041 ]]
Hallo
63.42113953261637
[[-0.7644734   2.68614617]]
[[ 0.143

[[-0.75802485  2.67920994]]
[[ 0.13916257 -0.21614799]
 [ 0.00851346 -0.02360947]]
Hallo
63.25561789441083
[[-0.75799522  2.67917659]]
[[ 0.13914406 -0.21612086]
 [ 0.00853172 -0.02364147]]
Hallo
63.254835975883516
[[-0.7579656   2.67914323]]
[[ 0.13912557 -0.21609375]
 [ 0.00854999 -0.02367347]]
Hallo
63.254054081224524
[[-0.75793598  2.67910987]]
[[ 0.13910709 -0.21606666]
 [ 0.00856825 -0.02370547]]
Hallo
63.25327221043193
[[-0.75790638  2.6790765 ]]
[[ 0.13908862 -0.21603958]
 [ 0.00858652 -0.02373748]]
Hallo
63.25249036350398
[[-0.75787679  2.67904314]]
[[ 0.13907016 -0.21601252]
 [ 0.00860478 -0.0237695 ]]
Hallo
63.25170854043869
[[-0.75784721  2.67900977]]
[[ 0.13905171 -0.21598548]
 [ 0.00862304 -0.02380152]]
Hallo
63.25092674123427
[[-0.75781763  2.67897639]]
[[ 0.13903327 -0.21595845]
 [ 0.0086413  -0.02383355]]
Hallo
63.25014496588879
[[-0.75778807  2.67894302]]
[[ 0.13901484 -0.21593144]
 [ 0.00865956 -0.02386559]]
Hallo
63.24936321440047
[[-0.75775852  2.67890964]]
[[ 0.13

63.12458896323235
[[-0.75314602  2.67353601]]
[[ 0.13617784 -0.21179358]
 [ 0.01159372 -0.02909916]]
Hallo
63.12381102853842
[[-0.75311788  2.67350224]]
[[ 0.136161   -0.21176915]
 [ 0.01161191 -0.02913212]]
Hallo
63.12303311740185
[[-0.75308976  2.67346846]]
[[ 0.13614417 -0.21174473]
 [ 0.0116301  -0.02916508]]
Hallo
63.122255229820745
[[-0.75306164  2.67343468]]
[[ 0.13612735 -0.21172033]
 [ 0.01164829 -0.02919805]]
Hallo
63.12147736579335
[[-0.75303353  2.67340089]]
[[ 0.13611054 -0.21169595]
 [ 0.01166649 -0.02923102]]
Hallo
63.12069952531779
[[-0.75300542  2.67336711]]
[[ 0.13609374 -0.21167157]
 [ 0.01168468 -0.029264  ]]
Hallo
63.1199217083922
[[-0.75297733  2.67333332]]
[[ 0.13607694 -0.21164722]
 [ 0.01170287 -0.02929698]]
Hallo
63.11914391501477
[[-0.75294924  2.67329953]]
[[ 0.13606016 -0.21162288]
 [ 0.01172106 -0.02932997]]
Hallo
63.118366145183685
[[-0.75292116  2.67326574]]
[[ 0.13604338 -0.21159855]
 [ 0.01173925 -0.02936297]]
Hallo
63.117588398897055
[[-0.75289309  2.

62.93701145860486
[[-0.7465615   2.66530545]]
[[ 0.1323609  -0.20630278]
 [ 0.01598723 -0.03721912]]
Hallo
62.936239171551044
[[-0.74653517  2.66527124]]
[[ 0.13234615 -0.20628176]
 [ 0.01600535 -0.03725323]]
Hallo
62.93546690761383
[[-0.74650884  2.66523702]]
[[ 0.13233141 -0.20626076]
 [ 0.01602347 -0.03728735]]
Hallo
62.93469466679139
[[-0.74648252  2.6652028 ]]
[[ 0.13231667 -0.20623977]
 [ 0.01604159 -0.03732147]]
Hallo
62.9339224490819
[[-0.74645621  2.66516858]]
[[ 0.13230194 -0.20621879]
 [ 0.01605971 -0.03735559]]
Hallo
62.933150254483564
[[-0.7464299   2.66513435]]
[[ 0.13228722 -0.20619783]
 [ 0.01607783 -0.03738972]]
Hallo
62.9323780829946
[[-0.7464036   2.66510013]]
[[ 0.13227251 -0.20617687]
 [ 0.01609595 -0.03742386]]
Hallo
62.93160593461314
[[-0.74637731  2.6650659 ]]
[[ 0.13225781 -0.20615594]
 [ 0.01611407 -0.037458  ]]
Hallo
62.93083380933739
[[-0.74635103  2.66503168]]
[[ 0.13224311 -0.20613501]
 [ 0.01613219 -0.03749214]]
Hallo
62.93006170716558
[[-0.74632475  2.66

62.757689609782894
[[-0.74059799  2.65729864]]
[[ 0.12912838 -0.20174309]
 [ 0.02020171 -0.04527417]]
Hallo
62.75692266008298
[[-0.7405731   2.65726416]]
[[ 0.12911535 -0.20172491]
 [ 0.02021977 -0.04530916]]
Hallo
62.75615573307932
[[-0.74054821  2.65722966]]
[[ 0.12910232 -0.20170674]
 [ 0.02023782 -0.04534416]]
Hallo
62.75538882877004
[[-0.74052333  2.65719517]]
[[ 0.1290893  -0.20168859]
 [ 0.02025587 -0.04537917]]
Hallo
62.754621947153325
[[-0.74049846  2.65716068]]
[[ 0.12907629 -0.20167044]
 [ 0.02027393 -0.04541417]]
Hallo
62.75385508822744
[[-0.74047359  2.65712619]]
[[ 0.12906329 -0.20165231]
 [ 0.02029198 -0.04544918]]
Hallo
62.753088251990576
[[-0.74044872  2.65709169]]
[[ 0.12905029 -0.20163419]
 [ 0.02031003 -0.0454842 ]]
Hallo
62.75232143844091
[[-0.74042387  2.6570572 ]]
[[ 0.1290373  -0.20161608]
 [ 0.02032808 -0.04551921]]
Hallo
62.751554647576604
[[-0.74039902  2.6570227 ]]
[[ 0.12902431 -0.20159798]
 [ 0.02034613 -0.04555423]]
Hallo
62.75078787939592
[[-0.74037417  

[[-0.735608    2.65021279]]
[[ 0.12659309 -0.19824326]
 [ 0.02389535 -0.05251264]]
Hallo
62.6001746188132
[[-0.73558418  2.65017816]]
[[ 0.12658137 -0.19822726]
 [ 0.02391333 -0.05254824]]
Hallo
62.59941230655025
[[-0.73556038  2.65014354]]
[[ 0.12656965 -0.19821127]
 [ 0.02393131 -0.05258384]]
Hallo
62.598650016613064
[[-0.73553657  2.65010891]]
[[ 0.12655793 -0.19819529]
 [ 0.02394929 -0.05261945]]
Hallo
62.597887748999845
[[-0.73551278  2.65007428]]
[[ 0.12654622 -0.19817931]
 [ 0.02396726 -0.05265505]]
Hallo
62.5971255037088
[[-0.73548898  2.65003965]]
[[ 0.12653452 -0.19816335]
 [ 0.02398524 -0.05269066]]
Hallo
62.59636328073814
[[-0.73546519  2.65000502]]
[[ 0.12652283 -0.1981474 ]
 [ 0.02400322 -0.05272627]]
Hallo
62.595601080086034
[[-0.73544141  2.6499704 ]]
[[ 0.12651114 -0.19813146]
 [ 0.02402119 -0.05276189]]
Hallo
62.594838901750705
[[-0.73541763  2.64993577]]
[[ 0.12649945 -0.19811553]
 [ 0.02403917 -0.05279751]]
Hallo
62.59407674573036
[[-0.73539386  2.64990114]]
[[ 0.12

62.44588050645511
[[-0.73084678  2.64314218]]
[[ 0.12431895 -0.19517657]
 [ 0.02755348 -0.05982227]]
Hallo
62.44512268948692
[[-0.73082389  2.6431075 ]]
[[ 0.12430836 -0.19516247]
 [ 0.02757136 -0.05985831]]
Hallo
62.44436489447982
[[-0.73080101  2.64307282]]
[[ 0.12429778 -0.19514839]
 [ 0.02758924 -0.05989436]]
Hallo
62.44360712143204
[[-0.73077814  2.64303814]]
[[ 0.1242872  -0.19513431]
 [ 0.02760712 -0.0599304 ]]
Hallo
62.44284937034175
[[-0.73075527  2.64300346]]
[[ 0.12427662 -0.19512024]
 [ 0.027625   -0.05996645]]
Hallo
62.442091641207185
[[-0.7307324   2.64296878]]
[[ 0.12426605 -0.19510618]
 [ 0.02764288 -0.06000249]]
Hallo
62.44133393402656
[[-0.73070954  2.64293409]]
[[ 0.12425549 -0.19509213]
 [ 0.02766075 -0.06003854]]
Hallo
62.440576248798045
[[-0.73068668  2.64289941]]
[[ 0.12424493 -0.19507809]
 [ 0.02767863 -0.0600746 ]]
Hallo
62.43981858551984
[[-0.73066383  2.64286473]]
[[ 0.12423438 -0.19506406]
 [ 0.02769651 -0.06011065]]
Hallo
62.43906094419018
[[-0.73064098  2.

62.300026609058925
[[-0.72650545  2.63644914]]
[[ 0.12236749 -0.19261258]
 [ 0.03099337 -0.06680703]]
Hallo
62.29927299732207
[[-0.72648333  2.63641447]]
[[ 0.12235784 -0.19260008]
 [ 0.03101113 -0.06684335]]
Hallo
62.298519407199905
[[-0.72646122  2.63637981]]
[[ 0.1223482  -0.19258759]
 [ 0.03102889 -0.06687967]]
Hallo
62.297765838690665
[[-0.72643911  2.63634514]]
[[ 0.12233856 -0.1925751 ]
 [ 0.03104665 -0.06691599]]
Hallo
62.29701229179254
[[-0.726417    2.63631047]]
[[ 0.12232893 -0.19256263]
 [ 0.03106441 -0.06695231]]
Hallo
62.29625876650373
[[-0.7263949   2.63627581]]
[[ 0.1223193  -0.19255016]
 [ 0.03108216 -0.06698864]]
Hallo
62.29550526282244
[[-0.7263728   2.63624114]]
[[ 0.12230967 -0.1925377 ]
 [ 0.03109992 -0.06702496]]
Hallo
62.29475178074689
[[-0.72635071  2.63620647]]
[[ 0.12230005 -0.19252525]
 [ 0.03111768 -0.06706129]]
Hallo
62.29399832027525
[[-0.72632862  2.63617181]]
[[ 0.12229044 -0.19251281]
 [ 0.03113543 -0.06709761]]
Hallo
62.29324488140577
[[-0.72630653  2

62.14298888461757
[[-0.72196024  2.62921059]]
[[ 0.12044651 -0.1901629 ]
 [ 0.03468902 -0.07441626]]
Hallo
62.14223975139734
[[-0.72193885  2.629176  ]]
[[ 0.12043776 -0.19015193]
 [ 0.03470662 -0.07445273]]
Hallo
62.141490639417434
[[-0.72191746  2.62914141]]
[[ 0.12042901 -0.19014097]
 [ 0.03472421 -0.07448921]]
Hallo
62.14074154867605
[[-0.72189608  2.62910682]]
[[ 0.12042027 -0.19013002]
 [ 0.03474181 -0.07452568]]
Hallo
62.13999247917139
[[-0.7218747   2.62907223]]
[[ 0.12041153 -0.19011907]
 [ 0.0347594  -0.07456215]]
Hallo
62.139243430901665
[[-0.72185332  2.62903764]]
[[ 0.1204028  -0.19010813]
 [ 0.034777   -0.07459862]]
Hallo
62.13849440386512
[[-0.72183194  2.62900305]]
[[ 0.12039407 -0.1900972 ]
 [ 0.03479459 -0.0746351 ]]
Hallo
62.13774539805991
[[-0.72181057  2.62896846]]
[[ 0.12038534 -0.19008627]
 [ 0.03481218 -0.07467157]]
Hallo
62.136996413484326
[[-0.7217892   2.62893387]]
[[ 0.12037662 -0.19007535]
 [ 0.03482978 -0.07470805]]
Hallo
62.13624745013648
[[-0.72176784  2

61.998052539236504
[[-0.71786865  2.62251084]]
[[ 0.11882089 -0.18815891]
 [ 0.03808562 -0.0814945 ]]
Hallo
61.997307493204275
[[-0.71784785  2.62247637]]
[[ 0.11881287 -0.1881492 ]
 [ 0.03810303 -0.08153098]]
Hallo
61.996562468066145
[[-0.71782705  2.6224419 ]]
[[ 0.11880485 -0.1881395 ]
 [ 0.03812044 -0.08156746]]
Hallo
61.99581746382042
[[-0.71780626  2.62240743]]
[[ 0.11879684 -0.1881298 ]
 [ 0.03813785 -0.08160393]]
Hallo
61.99507248046529
[[-0.71778547  2.62237296]]
[[ 0.11878883 -0.18812011]
 [ 0.03815526 -0.08164041]]
Hallo
61.99432751799897
[[-0.71776468  2.6223385 ]]
[[ 0.11878083 -0.18811042]
 [ 0.03817267 -0.08167689]]
Hallo
61.99358257641969
[[-0.7177439   2.62230403]]
[[ 0.11877283 -0.18810074]
 [ 0.03819008 -0.08171337]]
Hallo
61.992837655725666
[[-0.71772311  2.62226956]]
[[ 0.11876483 -0.18809107]
 [ 0.03820748 -0.08174984]]
Hallo
61.992092755915095
[[-0.71770233  2.6222351 ]]
[[ 0.11875683 -0.18808141]
 [ 0.03822489 -0.08178632]]
Hallo
61.991347876986204
[[-0.71768156

61.86946893193592
[[-0.71431152  2.61655918]]
[[ 0.11748454 -0.1865674 ]
 [ 0.04108172 -0.08779812]]
Hallo
61.8687274741693
[[-0.71429119  2.61652485]]
[[ 0.1174771  -0.1865587 ]
 [ 0.04109894 -0.08783449]]
Hallo
61.86798603698991
[[-0.71427087  2.61649053]]
[[ 0.11746967 -0.18655   ]
 [ 0.04111615 -0.08787087]]
Hallo
61.867244620396015
[[-0.71425054  2.6164562 ]]
[[ 0.11746224 -0.18654131]
 [ 0.04113337 -0.08790725]]
Hallo
61.86650322438583
[[-0.71423022  2.61642187]]
[[ 0.11745481 -0.18653263]
 [ 0.04115059 -0.08794362]]
Hallo
61.86576184895762
[[-0.7142099   2.61638755]]
[[ 0.11744739 -0.18652395]
 [ 0.0411678  -0.08798   ]]
Hallo
61.86502049410957
[[-0.71418959  2.61635322]]
[[ 0.11743996 -0.18651528]
 [ 0.04118501 -0.08801637]]
Hallo
61.86427915983998
[[-0.71416927  2.6163189 ]]
[[ 0.11743255 -0.18650661]
 [ 0.04120222 -0.08805275]]
Hallo
61.863537846147025
[[-0.71414896  2.61628458]]
[[ 0.11742513 -0.18649795]
 [ 0.04121944 -0.08808912]]
Hallo
61.862796553028936
[[-0.71412865  2.

 [ 0.04483937 -0.095775  ]]
Hallo
61.70610411308944
[[-0.7098789   2.60899616]]
[[ 0.11591517 -0.18477367]
 [ 0.0448563  -0.09581111]]
Hallo
61.70536716229017
[[-0.7098591   2.60896205]]
[[ 0.1159084  -0.18476612]
 [ 0.04487323 -0.09584722]]
Hallo
61.704630231689684
[[-0.70983931  2.60892794]]
[[ 0.11590162 -0.18475857]
 [ 0.04489016 -0.09588333]]
Hallo
61.703893321286245
[[-0.70981952  2.60889384]]
[[ 0.11589485 -0.18475103]
 [ 0.04490709 -0.09591944]]
Hallo
61.70315643107811
[[-0.70979974  2.60885974]]
[[ 0.11588808 -0.1847435 ]
 [ 0.04492402 -0.09595554]]
Hallo
61.70241956106354
[[-0.70977995  2.60882563]]
[[ 0.11588132 -0.18473597]
 [ 0.04494094 -0.09599165]]
Hallo
61.70168271124078
[[-0.70976017  2.60879153]]
[[ 0.11587455 -0.18472844]
 [ 0.04495787 -0.09602775]]
Hallo
61.70094588160809
[[-0.70974039  2.60875743]]
[[ 0.11586779 -0.18472092]
 [ 0.04497479 -0.09606385]]
Hallo
61.70020907216372
[[-0.70972061  2.60872333]]
[[ 0.11586104 -0.1847134 ]
 [ 0.04499171 -0.09609995]]
Hallo
6

In [20]:
print(loss(X_test, t_test, W1, W2))

18.199888128990136


In [21]:
print(forwardPassing(X_test, W1, W2)[2].T.shape)
print(len(t_test))

(45, 1)
45


In [22]:
from sklearn.metrics import r2_score
print(r2_score(forwardPassing(X_test, W1, W2)[2].T, t_test))

0.8653057510023083
